"""empty message

Revision ID: 7a7063ef1ab6
Revises: cde3a25e8f76
Create Date: 2025-07-24 17:28:54.945096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a7063ef1ab6'
down_revision: Union[str, Sequence[str], None] = 'cde3a25e8f76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('selected_indices', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('category_asked', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_results_id'), 'results', ['id'], unique=False)
    #op.alter_column('image_paths', 'uuid',
    #           existing_type=sa.NUMERIC(),
    #           type_=sa.UUID(),
    #           existing_nullable=False)
    """
    op.alter_column('unclassified_feedback', 'image_uuid',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    """
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('unclassified_feedback', 'image_uuid',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('image_paths', 'uuid',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_index(op.f('ix_results_id'), table_name='results')
    op.drop_table('results')
    # ### end Alembic commands ###
